# Generated by Django 4.2.3 on 2025-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('nao_planejada', 'Não Planejada'), ('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('finalizada', 'Finalizada')], default='nao_planejada', max_length=20),
        ),
    ]
