# Generated by Django 4.2.3 on 2025-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Planejada', 'Planejada'), ('Em andamento', 'Em andamento'), ('Aguardando aprovação', 'Aguardando aprovação'), ('Concluída', 'Concluída')], default='Pendente', max_length=20),
        ),
    ]
