# Generated by Django 4.2.3 on 2025-03-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_arquivamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivamento',
            old_name='data_arquivamento',
            new_name='arquivada_em',
        ),
        migrations.RemoveField(
            model_name='arquivamento',
            name='arquivada',
        ),
    ]
