# Generated by Django 4.2.3 on 2025-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_rename_data_arquivamento_arquivamento_arquivada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivamento',
            name='Status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Planejada', 'Planejada'), ('Em andamento', 'Em andamento'), ('Aguardando aprovação', 'Aguardando aprovação'), ('Concluída', 'Concluída')], default='Concluída', max_length=20),
        ),
    ]
