# Generated by Django 4.2.3 on 2025-03-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_arquivamento_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivamento',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
