# Generated by Django 4.2.3 on 2025-03-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_rename_status_arquivamento_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivamento',
            old_name='status',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida_em',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
